### ISSUE TITLE
driver not working with Panasonic S1

### ISSUE THREAD

**Issue by davidenitti** [totoantibes/LumixCameraAscomDriver#2]
I have problems with the driver (release v7.0 7bd21bd) on a Panasonic S1 
no matter which option I choose I have an error:
![Screenshot 2021-02-13 121933](https://user-images.githubusercontent.com/7438184/107849225-27af8d00-6dfa-11eb-997c-7923761dd3d1.png)
![Screenshot 2021-02-13 122038](https://user-images.githubusercontent.com/7438184/107849217-21b9ac00-6dfa-11eb-83a6-fb8f2e380842.png)

**Comment by davidenitti** [comment]
I fixed this issue, I close it

**Comment by totoantibes** [comment]
thx. Could you share how you fixed it?  I believe that the camera is not properly discovered (there is  no info in the "Camera Model"  and resolution is not correct for S1...

**Comment by davidenitti** [comment]
so basically I had on my tablet a big font and I couldn't properly config all the fields and press ok. with a smaller font I configured everthing and I don't have this error anymore.
however now sharpcap crashes when I start the camera, I'll open another issue later.
