### ISSUE TITLE
Lumix G9 Sensor Size

### ISSUE THREAD

**Issue by jonnybravo0311** [totoantibes/LumixCameraAscomDriver#3]
Hello Robert. I'm following up on the conversations we've had via email regarding the driver and my Lumix G9. As stated, the driver works if I use the "thumb" since you're forcing the resolution to something the camera is capable of providing. However, the given resolution for the 20.3 MP sensor in Driver.vb does not work for the G9. Looking at the information in digicamdb.com, the G9 is listed as a 20.33 MP sensor with a resolution of 5200 x 3910.

Would it be possible to add a new resolution choice of 20.33 MP to the Driver.vb code (and wherever else necessary)? Something like this:

`Resolutions(8)._resolution = "20.33"
Resolutions(8)._X = 5200
Resolutions(8)._Y = 3910`

and 

`ResolutionsJPG(8)._resolution = "20.33"
ResolutionsJPG(8)._X = 5200
ResolutionsJPG(8)._Y = 3910`

and

`ResolutionsThumb(8)._resolution = "20.33"
ResolutionsThumb(8)._X = 5200
ResolutionsThumb(8)._Y = 3910`

Then, change the G9 definition in the models:

`If Models.Contains("GX9") = False Then
Models.Add("GX9", "20.3")
Models.Add("GF10", "16.0")
Models.Add("GH5S", "10.2")
Models.Add("G9", "20.33")
Models.Add("GH5", "20.3")
Models.Add("GF9", "16.0")`

Add it to the resolution table:

`Public Shared ResolutionTable = {"10.2", "12.1", "16.0", "16.05", "20.0", "20.3", "20.33", "24.2", "47.3"}`

Not sure if there are any other places that would need to be changed.

Thanks in advance!

**Comment by totoantibes** [comment]
Jonny,  thanks for hashing it out.  I will look at it and post an update soon. 


Robert

**Comment by totoantibes** [comment]
After further investigation there was no need to add a new resolution entry in the driver.
I had only to map the g9 to 20.0 which held the correct dimensions as per: https://www.digicamdb.com/specs/panasonic_lumix-dc-g9/

If you find you still have issues with the new driver, you can pick the correct resolution from the drop-down list and override the one suggested by the camera discovery routine. 

The updated driver is now avail in the latest release: https://github.com/totoantibes/LumixCameraAscomDriver/releases/tag/7.0.2
