### ISSUE TITLE
Can't see all of properties dialogue.

### ISSUE THREAD

**Issue by marcbunyan** [totoantibes/LumixCameraAscomDriver#5]
Hi,

My imaging laptop isn't 1080p so I can't see all of the properties.

![image](https://user-images.githubusercontent.com/45541470/115542795-c07bf080-a2f4-11eb-9e5f-2356eb054a74.png)

i'm not sure If i have the right things selected at the missing bottom part - but the GX8 doesn't seem to appear as a detected camera so nothing will use the drivers/camera correctly so far.

**Comment by totoantibes** [comment]
on the driver setup form i have witnessed it also and not quite sure what this is due. My guess is that there is an issue with the compatibility mode of the calling app.. the bottom of the screen only shows an OK/Çancel that you can "tab"to and hit "enter"....

on the GX8 not picked up i am thinking that it is not discovered on the local network. check if the IP that is listed (224.0.0.22 is in fact he one of your gx8 camera). this happens some times when the camera is the hotspot that the PC is connecting to. What i find as a workaround is to first connect to the camera from your pana smartphone app to activate the remote control mode on the camera then switch the PC.

**Comment by totoantibes** [comment]
please try the latest release it may help with seeing the whole window and also warn in case the camera is not discovered on the network
